basePath: /
host: localhost:3000
info:
  contact:
    email: sukhum_butrkam@hotmail.com
    name: Sukhum Butrkam
  description: This is a sample swagger for Training Kawaii Shop
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Training Kawaii Shop API
  version: "1.0"
paths: {}
swagger: "2.0"
